from selenium.webdriver.common.by import By

class MainLocators:
    NAME = [By.XPATH, ".//input[@placeholder='* Имя']"] 
    LASTNAME = [By.XPATH, ".//input[@placeholder='* Фамилия']"]
    ADDRESS = [By.XPATH, ".//input[@placeholder='* Адрес: куда привезти заказ']"] 
    METRO = [By.XPATH, ".//input[@placeholder='* Станция метро']"] 
    PHONE = [By.XPATH, ".//input[@placeholder='* Телефон: на него позвонит курьер']"] 
    CHOOSE_METRO = [By.XPATH, ".//li[@data-value={num}]"] 
    ORDER_BUTTON_TOP = [By.XPATH, ".//div[contains(@class, 'Header_Nav')]/button[text()='Заказать']"] 
    LOGO_SAMOCAT = [By.XPATH, ".//img[@alt='Scooter']"] 
    LOGO_YANDEX = [By.XPATH, ".//img[@alt='Yandex']"]
    COOKIE_APPLY = [By.ID, "rcc-confirm-button"]
    QUESTION = [By.ID, "accordion__heading-{}"] 
    ANSWER = [By.ID, "accordion__panel-{}"] 
    IMPORTANT_QUESTIONS = [By.XPATH, ".//div[text()='Вопросы о важном']"] 
    ORDER_BUTTON_ON_DOWN = [By.XPATH, ".//div[contains(@class, 'Home_FinishButton')]/button[text()='Заказать']"] 
    HEADER_ON_MAIN = [By.XPATH, ".//div[contains(@class, 'Home_Header')]"] 
    ORDER_BUTTON_ON_TOP = [By.XPATH, ".//div[contains(@class, 'Header_Nav')]/button[text()='Заказать']"] 
    LOGO_SCOOTER = [By.XPATH, ".//img[@alt='Scooter']"] 
    COOKIE_BUTTON = [By.ID, "rcc-confirm-button"] 
    DZEN_HEADER = [By.ID, "dzen-header"] 
    ORDER_TITLE_FIRST = [By.XPATH, ".//div[text()='Для кого самокат']"] 
    ONWARD_BUTTON = [By.XPATH, ".//button[text()='Далее']"] 
    ORDER_TITLE_SECOND = [By.XPATH, ".//div[text()='Про аренду']"] 
    WHEN_BACK = [By.XPATH, ".//input[@placeholder='* Когда привезти самокат']"] 
    CHOOSE_DATE = (By.XPATH, ".//div[contains(@class, 'selected')]") 
    CHOOSE_LIMIT = [By.CLASS_NAME, "Dropdown-option"] 
    CHOOSE_SAMOCAT = [By.XPATH, ".//label[contains(@class, 'Checkbox_Label')]"] 
    LIMIT = [By.XPATH, ".//div[text()='* Срок аренды']"] 
    COMMENT = [By.XPATH, ".//input[@placeholder='Комментарий для курьера']"] 
    BUTTON_ORDER = [By.XPATH, ".//div[contains(@class, 'Order_Buttons')]/button[text()='Заказать']"] 
    CONFIRM_WINDOW = [By.XPATH, ".//div[contains(@class, 'Order_ModalHeader')]"]
    YES_BUTTON = [By.XPATH, ".//button[text()='Да']"] 
    STATUS_BUTTON = [By.XPATH, ".//button[text()='Посмотреть статус']"] 
    CANCEL_BUTTON = [By.XPATH, ".//button[text()='Отменить заказ']"]